if(file.exists("RandomWalk_cbr.csv"))
  file.remove("RandomWalk_cbr.csv")
if(file.exists("ConstantPosition_cbr.csv"))
  file.remove("ConstantPosition_cbr.csv")
file.create("ConstantPosition_cbr.csv")
if(file.exists("RandomWalk_pulse.csv"))
  file.remove("RandomWalk_pulse.csv")
if(file.exists("ConstantPosition_pulse_cbr.csv"))
  file.remove("ConstantPosition_pulse_cbr.csv")
if(file.exists("Nearest_node_cbr.csv"))
  file.remove("Nearest_node_cbr.csv")
if(file.exists("Nearest_node_pulse.csv"))
  file.remove("Nearest_node_pulse.csv")
if(file.exists("Farthest_node_cbr.csv"))
  file.remove("Farthest_node_cbr.csv")
if(file.exists("Farthest_node_pulse.csv"))
  file.remove("Farthest_node_pulse.csv")

for (i in seq(from=5, to=40, by=5)){
  print(paste ('Nos=',  i))
  print("CBR e nos fixos")
  system(paste("NS_GLOBAL_VALUE=\"RngRun=3\" ./waf --run \"scratch/wifiinfra --nodes=",i," --runningTime=20 --traffic=true --mobility=false --printLog=false\"", collapse=", ", sep=""))
  print("CBR e nos moveis")
  system(paste("NS_GLOBAL_VALUE=\"RngRun=3\" ./waf --run \"scratch/wifiinfra --nodes=",i," --runningTime=120 --traffic=true --mobility=true\" --printLog=false\"", collapse=", ", sep=""))
  print("Rajada e nos fixos")
  system(paste("NS_GLOBAL_VALUE=\"RngRun=3\" ./waf --run \"scratch/wifiinfra --nodes=",i," --runningTime=120 --traffic=false --mobility=false\" --printLog=false\"", collapse=", ", sep=""))
  print("Rajada e nos moveis")
  system(paste("NS_GLOBAL_VALUE=\"RngRun=3\" ./waf --run \"scratch/wifiinfra --nodes=",i," --runningTime=120 --traffic=false --mobility=true\" --printLog=false\"", collapse=", ", sep=""))
}

rw_cbr <- read.csv("RandomWalk_cbr.csv", header=F, sep=";")
cp_cbr <- read.csv("ConstantPosition_cbr.csv", header=F, sep=";")
rw_pulse <- read.csv("RandomWalk_pulse.csv", header=F, sep=";")
cp_pulse <- read.csv("ConstantPosition_pulse_cbr.csv", header=F, sep=";")
n_cbr <- read.csv("Nearest_node_cbr.csv", header=F, sep=";")
n_pulse <- read.csv("Nearest_node_pulse.csv", header=F, sep=";")
f_cbr <- read.csv("Farthest_node_cbr.csv", header=F, sep=";")
f_pulse <- read.csv("Farthest_node_pulse.csv", header=F, sep=";")


#graficos dos nos mais perto e mais distante do AP
pdf("Throughput_static.pdf")
plot(cp_cbr[,1], cp_cbr[,2], xlab='Número de nós', ylim=c(min(range(cp_cbr[,2]), range(n_cbr[,3]), range(f_cbr[,3]), range(cp_pulse[,2]), range(n_pulse[,3]), range(f_pulse[,3])), max(range(cp_cbr[,2]), range(n_cbr[,3]), range(f_cbr[,3]), range(cp_pulse[,2]), range(n_pulse[,3]), range(f_pulse[,3]))), ylab='Throughput em kbts', xaxp=c(5,40,7), type="b", col="blue", lwd=2, pch=19, main='Throughput')
points(n_cbr[,1], n_cbr[,3], type='b', col='green', lwd=2, pch=18)
points(f_cbr[,1], f_cbr[,3], type='b', col='red', lwd=2, pch=17)
points(ap_cbr[,1], cp_pulse[,2], type='b', col='orange', lwd=2, pch=16)
points(f_cbr[,1], f_pulse[,3], type='b', col='purple', lwd=2, pch=15)
points(n_cbr[,1], n_pulse[,3], type='b', col='yellow', lwd=2, pch=14)
grid(col='black')
legend('topleft', legend=c('CBR/Média', 'CBR/Nearest', 'CBR/Farthest', 'Rajada/Média', 'Rajada/Nearest', 'Rajada/Farthest'), lwd=2, pch=c(19, 18, 17, 16, 15, 14), title='Protocolo/Parametro', bg='white', col=c('blue', 'green', 'red', 'orange', 'purple', 'yellow'))
dev.off()

pdf("Delay_static.pdf")
plot(cp_cbr[,1], cp_cbr[,3], xlab='Número de nós', ylim=c(min(range(cp_cbr[,3]), range(n_cbr[,4]), range(f_cbr[,4]), range(cp_pulse[,3]), range(n_pulse[,4]), range(f_pulse[,4])), max(range(cp_cbr[,3]), range(n_cbr[,4]), range(f_cbr[,4]), range(cp_pulse[,3]), range(n_pulse[,4]), range(f_pulse[,4]))), ylab='Delay em ms', xaxp=c(5,40,7), type="b", col="blue", lwd=2, pch=19, main='Delay')
points(n_cbr[,1], n_cbr[,4], type='b', col='green', lwd=2, pch=18)
points(f_cbr[,1], f_cbr[,4], type='b', col='red', lwd=2, pch=17)
points(ap_cbr[,1], cp_pulse[,3], type='b', col='orange', lwd=2, pch=16)
points(f_cbr[,1], f_pulse[,4], type='b', col='purple', lwd=2, pch=15)
points(n_cbr[,1], n_pulse[,4], type='b', col='yellow', lwd=2, pch=14)
grid(col='black')
legend('topleft', legend=c('CBR/Média', 'CBR/Nearest', 'CBR/Farthest', 'Rajada/Média', 'Rajada/Nearest', 'Rajada/Farthest'), lwd=2, pch=c(19, 18, 17, 16, 15, 14), title='Protocolo/Parametro', bg='white', col=c('blue', 'green', 'red', 'orange', 'purple', 'yellow'))
dev.off()

pdf("LostPackets_static.pdf")
plot(cp_cbr[,1], cp_cbr[,4], xlab='Número de nós', ylim=c(min(range(cp_cbr[,4]), range(n_cbr[,5]), range(f_cbr[,5]), range(cp_pulse[,4]), range(n_pulse[,5]), range(f_pulse[,5])), max(range(cp_cbr[,4]), range(n_cbr[,5]), range(f_cbr[,5]), range(cp_pulse[,4]), range(n_pulse[,5]), range(f_pulse[,5]))), ylab='Perca de pacotes', xaxp=c(5,40,7), type="b", col="blue", lwd=2, pch=19, main='Delay')
points(n_cbr[,1], n_cbr[,5], type='b', col='green', lwd=2, pch=18)
points(f_cbr[,1], f_cbr[,5], type='b', col='red', lwd=2, pch=17)
points(ap_cbr[,1], cp_pulse[,4], type='b', col='orange', lwd=2, pch=16)
points(f_cbr[,1], f_pulse[,5], type='b', col='purple', lwd=2, pch=15)
points(n_cbr[,1], n_pulse[,5], type='b', col='yellow', lwd=2, pch=14)
grid(col='black')
legend('topleft', legend=c('CBR/Média', 'CBR/Nearest', 'CBR/Farthest', 'Rajada/Média', 'Rajada/Nearest', 'Rajada/Farthest'), lwd=2, pch=c(19, 18, 17, 16, 15, 14), title='Protocolo/Parametro', bg='white', col=c('blue', 'green', 'red', 'orange', 'purple', 'yellow'))
dev.off()

#Graficos principais
pdf("Throughput_CBR_pulse.pdf")
plot(cp_cbr[,1], cp_cbr[,2], xlab='Número de nós', ylim=c(min(range(cp_cbr[,2]), range(cp_pulse[,2]), range(rw_cbr[,2]), range(rw_pulse[,2])), max(range(cp_cbr[,2]), range(cp_pulse[,2]), range(rw_cbr[,2]), range(rw_pulse[,2]))), ylab='Throughput médio em kbts', xaxp=c(5,40,7), type="b", col="blue", lwd=2, pch=19, main='Throughput médio')
points(rw_cbr[,1], rw_cbr[,2], type='b', col='green', lwd=2, pch=18)
points(cp_pulse[,1], cp_pulse[,2], type='b', col='red', lwd=2, pch=17)
points(rw_pulse[,1], rw_pulse[,2], type='b', col='orange', lwd=2, pch=16)
grid(col='black')
legend('topleft', legend=c('CBR/staticos', 'CBR/móveis', 'Rajada/estáticos', 'Rajada/móveis'), lwd=2, pch=c(19, 18, 17, 16), title='Protocolo/mobilidade dos nós', bg='white', col=c('blue','green', 'red', 'orange'))
dev.off()

pdf("Delay_CBR_pulse.pdf")
plot(cp_cbr[,1], cp_cbr[,3], xlab='Número de nós', ylim=c(min(range(cp_cbr[,3]), range(cp_pulse[,3]), range(rw_cbr[,3]), range(rw_pulse[,3])), max(range(cp_cbr[,3]), range(cp_pulse[,3]), range(rw_cbr[,3]), range(rw_pulse[,3]))), ylab='Delay médio em ms', xaxp=c(5,40,7), type="b", col="blue", lwd=2, pch=19, main='Delay médio')
points(rw_cbr[,1], rw_cbr[,3], type='b', col='green', lwd=2, pch=18)
points(cp_pulse[,1], cp_pulse[,3], type='b', col='red', lwd=2, pch=17)
points(rw_pulse[,1], rw_pulse[,3], type='b', col='orange', lwd=2, pch=16)
grid(col='black')
legend('topleft', legend=c('CBR/staticos', 'CBR/móveis', 'Rajada/estáticos', 'Rajada/móveis'), lwd=2, pch=c(19, 18, 17, 16), title='Protocolo/mobilidade dos nós', bg='white', col=c('blue','green', 'red', 'orange'))
dev.off()

pdf("LostPackets_CBR_pulse.pdf")
plot(cp_cbr[,1], cp_cbr[,4], xlab='Número de nós', ylim=c(min(range(cp_cbr[,4]), range(cp_pulse[,4]), range(rw_cbr[,4]), range(rw_pulse[,4])), max(range(cp_cbr[,4]), range(cp_pulse[,4]), range(rw_cbr[,4]), range(rw_pulse[,4]))), ylab='Perca média de pacotes', xaxp=c(5,40,7), type="b", col="blue", lwd=2, pch=19, main='Perca média de pacotes (valores absolutos)')
points(rw_cbr[,1], rw_cbr[,4], type='b', col='green', lwd=2, pch=18)
points(cp_pulse[,1], cp_pulse[,4], type='b', col='red', lwd=2, pch=17)
points(rw_pulse[,1], rw_pulse[,4], type='b', col='orange', lwd=2, pch=16)
grid(col='black')
legend('topleft', legend=c('CBR/staticos', 'CBR/móveis', 'Rajada/estáticos', 'Rajada/móveis'), lwd=2, pch=c(19, 18, 17, 16), title='Protocolo/mobilidade dos nós', bg='white', col=c('blue','green', 'red', 'orange'))
dev.off()

#Graficos individuais para o primeiro cenario(sem mobilidade)
pdf("Throughput_static_CBR.pdf")
plot(cp_cbr[,1], cp_cbr[,2], xlab='Número de nós', ylim=c(min(range(cp_cbr[,2]), range(n_cbr[,3]), range(f_cbr[,3])), max(range(cp_cbr[,2]), range(n_cbr[,3]), range(f_cbr[,3]))), ylab='Throughput em kbts', xaxp=c(5,40,7), type="b", col="blue", lwd=2, pch=19, main='Throughput CBR')
points(n_cbr[,1], n_cbr[,3], type='b', col='green', lwd=2, pch=18)
points(f_cbr[,1], f_cbr[,3], type='b', col='red', lwd=2, pch=17)
grid(col='black')
legend('topleft', legend=c('Média', 'Nearest', 'Farthest'), lwd=2, pch=c(19, 18, 17), title='Parametros', bg='white', col=c('blue', 'green', 'red'))
dev.off()

pdf("Throughput_static_pulse.pdf")
plot(cp_pulse[,1], cp_pulse[,2], xlab='Número de nós', ylim=c(min(range(cp_pulse[,2]), range(n_pulse[,3]), range(f_pulse[,3])), max(range(cp_pulse[,2]), range(n_pulse[,3]), range(f_pulse[,3]))), ylab='Throughput em kbits', xaxp=c(5,40,7), type="b", col="blue", lwd=2, pch=19, main='Throughput pulse')
points(n_pulse[,1], n_pulse[,3], type='b', col='green', lwd=2, pch=18)
points(f_pulse[,1], f_pulse[,3], type='b', col='red', lwd=2, pch=17)
grid(col='black')
legend('topleft', legend=c('Média', 'Nearest', 'Farthest'), lwd=2, pch=c(19, 18, 17), title='Parametros', bg='white', col=c('blue', 'green', 'red'))
dev.off()

pdf("DelayPackets_static_CBR.pdf")
plot(cp_cbr[,1], cp_cbr[,3], xlab='Número de nós', ylim=c(min(range(cp_cbr[,3]), range(n_cbr[,4]), range(f_cbr[,4])), max(range(cp_cbr[,3]), range(n_cbr[,4]), range(f_cbr[,4]))), ylab='Delay em ms', xaxp=c(5,40,7), type="b", col="blue", lwd=2, pch=19, main='Delay CBR')
points(n_cbr[,1], n_cbr[,4], type='b', col='green', lwd=2, pch=18)
points(f_cbr[,1], f_cbr[,4], type='b', col='red', lwd=2, pch=17)
grid(col='black')
legend('topleft', legend=c('Média', 'Nearest', 'Farthest'), lwd=2, pch=c(19, 18, 17), title='Parametros', bg='white', col=c('blue', 'green', 'red'))
dev.off()

pdf("DelayPackets_static_pulse.pdf")
plot(cp_pulse[,1], cp_pulse[,3], xlab='Número de nós', ylim=c(min(range(cp_pulse[,3]), range(n_pulse[,4]), range(f_pulse[,4])), max(range(cp_pulse[,3]), range(n_pulse[,4]), range(f_pulse[,4]))), ylab='Delay em ms', xaxp=c(5,40,7), type="b", col="blue", lwd=2, pch=19, main='Delay pulse')
points(n_pulse[,1], n_pulse[,4], type='b', col='green', lwd=2, pch=18)
points(f_pulse[,1], f_pulse[,4], type='b', col='red', lwd=2, pch=17)
grid(col='black')
legend('topleft', legend=c('Média', 'Nearest', 'Farthest'), lwd=2, pch=c(19, 18, 17), title='Parametros', bg='white', col=c('blue', 'green', 'red'))
dev.off()

pdf("LostPackets_static_CBR.pdf")
plot(cp_cbr[,1], cp_cbr[,4], xlab='Número de nós', ylim=c(min(range(cp_cbr[,4]), range(n_cbr[,5]), range(f_cbr[,5])), max(range(cp_cbr[,4]), range(n_cbr[,5]), range(f_cbr[,5]))), ylab='LostPackets em ms', xaxp=c(5,40,7), type="b", col="blue", lwd=2, pch=19, main='LostPackets CBR')
points(n_cbr[,1], n_cbr[,5], type='b', col='green', lwd=2, pch=18)
points(f_cbr[,1], f_cbr[,5], type='b', col='red', lwd=2, pch=17)
grid(col='black')
legend('topleft', legend=c('Média', 'Nearest', 'Farthest'), lwd=2, pch=c(19, 18, 17), title='Parametros', bg='white', col=c('blue', 'green', 'red'))
dev.off()

pdf("LostPackets_static_pulse.pdf")
plot(cp_pulse[,1], cp_pulse[,4], xlab='Número de nós', ylim=c(min(range(cp_pulse[,4]), range(n_pulse[,5]), range(f_pulse[,5])), max(range(cp_pulse[,4]), range(n_pulse[,5]), range(f_pulse[,3]))), ylab='LostPackets em ms', xaxp=c(5,40,7), type="b", col="blue", lwd=2, pch=19, main='LostPackets pulse')
points(n_pulse[,1], n_pulse[,5], type='b', col='green', lwd=2, pch=18)
points(f_pulse[,1], f_pulse[,5], type='b', col='red', lwd=2, pch=17)
grid(col='black')
legend('topleft', legend=c('Média', 'Nearest', 'Farthest'), lwd=2, pch=c(19, 18, 17), title='Parametros', bg='white', col=c('blue', 'green', 'red'))
dev.off()
